# Generated by Django 6.0.1 on 2026-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('kirvano', 'Kirvano'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='Origem')),
                ('event_id', models.CharField(help_text='ID único do evento para evitar duplicação', max_length=255, unique=True, verbose_name='ID do Evento')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Headers')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('processing_error', models.TextField(blank=True, verbose_name='Erro de Processamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='webhooks_we_source_d1bb98_idx'), models.Index(fields=['event_id'], name='webhooks_we_event_i_fd6344_idx'), models.Index(fields=['processed'], name='webhooks_we_process_cbb47e_idx')],
            },
        ),
    ]
