# Generated by Django 6.0.1 on 2026-02-14 15:00

import agenda.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=agenda.models.generate_agenda_identifier, max_length=10, unique=True, verbose_name='Identificador')),
                ('title', models.CharField(max_length=255, verbose_name='Título/Compromisso')),
                ('date_time', models.DateTimeField(verbose_name='Data e Hora')),
                ('notified_1h', models.BooleanField(default=False, verbose_name='Notificado 1h Antes')),
                ('notified_5min', models.BooleanField(default=False, verbose_name='Notificado 5min Antes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'ordering': ['date_time'],
                'indexes': [models.Index(fields=['user', 'date_time'], name='agenda_appo_user_id_e46f53_idx'), models.Index(fields=['notified_1h', 'notified_5min'], name='agenda_appo_notifie_7c2a99_idx')],
            },
        ),
    ]
