# Generated by Django 6.0.1 on 2026-02-13 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Remetente')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('audio', 'Áudio'), ('image', 'Imagem')], max_length=10, verbose_name='Tipo de Mensagem')),
                ('raw_content', models.TextField(blank=True, verbose_name='Conteúdo Original')),
                ('media_url', models.URLField(blank=True, null=True, verbose_name='URL da Mídia')),
                ('normalized_text', models.TextField(blank=True, verbose_name='Texto Normalizado')),
                ('status', models.CharField(choices=[('received', 'Recebida'), ('processing', 'Processando'), ('normalized', 'Normalizada'), ('routed', 'Roteada'), ('completed', 'Completada'), ('error', 'Erro')], default='received', max_length=20, verbose_name='Status')),
                ('intent', models.CharField(blank=True, max_length=100, verbose_name='Intenção Identificada')),
                ('debounce_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo de Debounce')),
                ('is_grouped', models.BooleanField(default=False, verbose_name='Agrupada')),
                ('response_sent', models.TextField(blank=True, verbose_name='Resposta Enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebida em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='whatsapp_me_user_id_804c64_idx'), models.Index(fields=['status'], name='whatsapp_me_status_375b3e_idx'), models.Index(fields=['debounce_group'], name='whatsapp_me_debounc_957631_idx')],
            },
        ),
    ]
