# Generated by Django 6.0.1 on 2026-02-13 18:24

import django.db.models.deletion
import django.utils.timezone
import transactions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=transactions.models.generate_identifier, max_length=20, unique=True, verbose_name='Identificador')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Transação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo Alterado')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor Antigo')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transactions.transaction', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Log de Transação',
                'verbose_name_plural': 'Logs de Transações',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-transaction_date'], name='transaction_user_id_64ff44_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='transaction_user_id_4685bf_idx'),
        ),
    ]
