# Generated by Django 6.0.1 on 2026-02-13 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kirvano_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Assinatura Kirvano')),
                ('plan_name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('pending', 'Pendente'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
