# Generated by Django 6.0.1 on 2026-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notified_expiration_warning',
            field=models.BooleanField(default=False, verbose_name='Notificado sobre Expiração'),
        ),
    ]
